### ISSUE TITLE
Add option to hide scrollbar

### ISSUE THREAD

**Issue by mojavelinux** [opendevise/bespoke-overview#10]
Instead of requiring the user to add the styles to hide the vertical scrollbar in the overview, the plugin should hide the dirty work behind an option and inject the necessary CSS into the page.

``` css
.bespoke-overview { -ms-overflow-style: none } // hide visible scrollbar in IE 10+
.bespoke-overview::-webkit-scrollbar { width: 0 } // hide visible scrollbar in WebKit
```

This would also allow us to accommodate hiding the scrollbar in Firefox, which is not possible using CSS alone.
