### ISSUE TITLE
Use user-select none instead of pointer events to disable image highlighting

### ISSUE THREAD

**Issue by mojavelinux** [opendevise/bespoke-overview#8]
In Firefox, when you click on a slide with an image, Firefox highlights the image. To work around this, we have been setting pointer-events: none on the image. However, this doesn't seem to work consistently. We should switch instead to "user-select: none". Specifically:

``` css
.bespoke-overview img{-moz-user-select:none}
```
